#!/bin/bash

echo "🚀 Деплой проекта на сервер..."

# Используем expect для автоматического ввода пароля
expect << 'EXPECT_SCRIPT'
spawn ssh -o StrictHostKeyChecking=no root@82.146.39.18
expect "password:"
send "lShzBqBqnsHcR2sUos8v4XT4\r"
expect "#"
send "cd /var/www/www-root/data/www/m.dekan.pro\r"
expect "#"
send "echo '📥 Обновляем код с GitHub...'\r"
expect "#"
send "git fetch origin\r"
expect "#"
send "git reset --hard origin/main\r"
expect "#"
send "echo '📦 Обновляем зависимости...'\r"
expect "#"
send "composer install --no-dev --optimize-autoloader\r"
expect "#"
send "echo '🧹 Очищаем кэш...'\r"
expect "#"
send "php artisan config:clear\r"
expect "#"
send "php artisan cache:clear\r"
expect "#"
send "php artisan view:clear\r"
expect "#"
send "echo '🗄️ Проверяем миграции...'\r"
expect "#"
send "php artisan migrate --force\r"
expect "#"
send "echo '⚡ Оптимизируем приложение...'\r"
expect "#"
send "php artisan config:cache\r"
expect "#"
send "php artisan route:cache\r"
expect "#"
send "php artisan view:cache\r"
expect "#"
send "echo '🔐 Устанавливаем права доступа...'\r"
expect "#"
send "chown -R www-data:www-data storage bootstrap/cache\r"
expect "#"
send "chmod -R 775 storage bootstrap/cache\r"
expect "#"
send "echo '✅ Деплой завершен!'\r"
expect "#"
send "exit\r"
expect eof
EXPECT_SCRIPT

echo "🌐 Проект обновлен на сервере: http://82.146.39.18"
